# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6d400dbaf94e310d93b78e75086aa4e476566232ed88839a4aae51691e8b69c043bb30f6f0acae9565ab1751e0db732c7c780ef53167de4914531dc73257026

test:
  secret_key_base: 2e88bf5913fae09b1b9372936b9a85f9e5a9f6a2db2ba06200b22d4c84f2ed5b6731a7c57444082a58478bd1ef03a5351b46b2060f4ee60638d742fdffef2b6c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
